---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```
# grass

<!-- badges: start -->
<!-- badges: end -->

grass (Genetic Regression Approximation through Summary Statistics) is an in-development R package to describe various regression models using only summary statistics.

Currently, grass supports the linear modeling of complex phenotypes defined via functions of other phenotypes.
Supported functions include:

* linear combinations (E.g. $\phi_1y_1 + \phi_2y_2$)
* products (E.g. $y_1\circ y_2$)
* logical combinations (E.g. $y_1\wedge y_2$ or $y_1\vee y_2$)

## Installation

You can install the in-development version of grass from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("jackmwolf/grass")
```
## Example


## References
Following are the key references for the functions in this package

* Wolf, J.M., Barnard, M. Xueting, X., Ryder, N., Westra, J., and Tintle, N. 
  (2020). Computationally efficient, exact, covariate-adjusted genetic principal
  component analysis by leveraging individual marker summary statistics from 
  large biobanks. *Pacific Symposium on Biocomputing*, 25, 719-730. 
* Gasdaska A., Friend D., Chen R., Westra J., Zawistowski M., Lindsey W. and 
  Tintle N. (2019) Leveraging summary statistics to make inferences about 
  complex phenotypes in large biobanks. *Pacific Symposium on Biocomputing*, 24, 
  391-402.
